import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="grid grid-cols-12">
                    <div className="border-b-2 border-b-black col-span-12 h-16 grid grid-cols-subgrid">
                        <div className="col-span-10 col-start-2 h-full">
                            
                        </div>
                    </div>
                    <div className="col-span-10 col-start-2 min-h-96 grid grid-cols-subgrid">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
